# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='heading',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='sub_heading',
            field=models.TextField(blank=True),
        ),
    ]
