# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('priced_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Priced')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=255)),
                ('no_of_servings', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shop.Product')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
            },
            bases=('shop.priced', models.Model),
        ),
    ]
