# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('cover_image', mezzanine.core.fields.FileField(max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Order Menu',
                'verbose_name_plural': 'Order Menus',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Menu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Product')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
