# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 00:37
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import migrations

from mezzanine.pages.models import RichTextPage


def create_product_list_page(apps, schema_editor):
    """
    Create a page whose and set the slug to  match the hardcoded the url for
    shop.views.product_list view so that mezzanine can pick it up and add it
    to page menus for navigation.
    """
    RichTextPage.objects.create(
        title="Todays's Menu",
        slug=reverse('shop:product:list').split('/')[1]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.RunPython(create_product_list_page),

    ]
