# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 16:31
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_menu_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('_order',), 'verbose_name': 'Delio Menu', 'verbose_name_plural': 'Delio Menus'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='cover_image',
            field=mezzanine.core.fields.FileField(max_length=255, verbose_name='Cover image'),
        ),
    ]
