# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170226_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Package',
        ),
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='PackageItem',
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('_order',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.RenameField(
            model_name='packageitem',
            old_name='menu',
            new_name='package',
        ),
    ]
