# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170306_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews_count',
            new_name='comments_count',
        ),
    ]
