# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 06:08
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170308_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
