# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 10:51
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import migrations

from mezzanine.pages.models import Page


def add_product_list_view_as_page(apps, schema_editor):
    """
    Create a 'mezzanine.pages.model.Page' page and set the slug
    to the 'shop.views.product_list' View url so that mezzanine
    can pick it up and add it to page_menus hierarchy for navigation.
    """
    Page.objects.create(
        title="Menu",
        slug=reverse('shop:product:list').split('/')[1]
    )

    
class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_package_content'),
    ]

    operations = [
        migrations.RunPython(add_product_list_view_as_page),
    ]
