# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='site',
        ),
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
